name: "Release New Version"

on:
  workflow_dispatch:
    inputs:
      release_title:
        description: 'Title for the release'
        required: true
      release_body:
        description: 'Additional release notes'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  publish:
    name: "Publish to NPM"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v2

      - name: "Set up Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          registry-url: "https://registry.npmjs.org/"

      - name: "Install dependencies"
        run: npm ci

      - name: "Build project"
        run: npm run build

      - name: "Fetch tags"
        run: git fetch --tags

      - name: "Get version info"
        id: version_info
        run: |
          CURRENT_TAG="v$(node -p "require('./package.json').version")"
          PREVIOUS_TAG=$(git tag --sort=-creatordate | grep '^v' | grep -v "$CURRENT_TAG" | head -n 1 || echo "")

          echo "current=$CURRENT_TAG" >> $GITHUB_OUTPUT
          echo "previous=$PREVIOUS_TAG" >> $GITHUB_OUTPUT

      - name: "Configure Git"
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: "Create Git tag"
        run: git tag ${{ steps.version_info.outputs.current }}

      - name: "Push tag"
        run: git push origin ${{ steps.version_info.outputs.current }}

      - name: "Publish to NPM"
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "Install GitHub CLI"
        run: sudo apt-get install gh

      - name: "Authenticate GitHub CLI"
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: "Fetch merged PRs between tags"
        id: fetch_prs
        run: |
          PREVIOUS_TAG=${{ steps.version_info.outputs.previous }}
          CURRENT_TAG=${{ steps.version_info.outputs.current }}

          # Get the commit SHAs for the tags
          PREVIOUS_SHA=$(git rev-list -n 1 $PREVIOUS_TAG)
          CURRENT_SHA=$(git rev-list -n 1 $CURRENT_TAG)

          # Get the merge dates for the tags
          PREVIOUS_DATE=$(git show -s --format=%cI $PREVIOUS_SHA)
          CURRENT_DATE=$(git show -s --format=%cI $CURRENT_SHA)

          # Fetch merged PRs between the two dates
          PR_LIST=$(gh pr list --state merged --search "merged:${PREVIOUS_DATE}..${CURRENT_DATE}" --json number,title,url --jq '.[] | "- [#\(.number)](\(.url)) \(.title)"')

          echo "pr_list<<EOF" >> $GITHUB_OUTPUT
          echo "$PR_LIST" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: "Create GitHub Release"
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version_info.outputs.current }}
          release_name: ${{ github.event.inputs.release_title }}
          body: |
            **Merged Pull Requests:**
            ${{ steps.fetch_prs.outputs.pr_list }}

            **Full Changelog:** https://github.com/${{ github.repository }}/compare/${{ steps.version_info.outputs.previous }}...${{ steps.version_info.outputs.current }}

            ${{ github.event.inputs.release_body }}

            Published by ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
