name: "Release New Version"

on:
  workflow_dispatch:
    inputs:
      release_title:
        description: 'Title for the release'
        required: true
      release_body:
        description: 'Content for the release notes'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  publish:
    name: "Publish to NPM and GitHub Release"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to fetch all tags

      - name: "Set up Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          registry-url: "https://registry.npmjs.org/"

      - name: "Install dependencies"
        run: npm ci

      - name: "Create build"
        run: npm run build

      - name: "Get current version from package.json"
        id: get_version
        run: |
          echo "version=v$(node -p 'require("./package.json").version')" >> $GITHUB_OUTPUT

      - name: "Get previous version tag"
        id: get_previous_tag
        run: |
          git fetch --tags
          PREV_TAG=$(git tag --sort=-creatordate | grep '^v' | grep -v "${{ steps.get_version.outputs.version }}" | head -n 1)
          echo "previous_tag=$PREV_TAG" >> $GITHUB_OUTPUT

      - name: "Set Git user"
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: "Create Git tag"
        run: git tag ${{ steps.get_version.outputs.version }}

      - name: "Push tag to origin"
        run: git push origin ${{ steps.get_version.outputs.version }}

      - name: "Publish to NPM"
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "Set release info"
        id: set_release_info
        run: |
          TITLE="${{ github.event.inputs.release_title }}"
          BODY="${{ github.event.inputs.release_body }}"
          VERSION="${{ steps.get_version.outputs.version }}"
          PREV_TAG="${{ steps.get_previous_tag.outputs.previous_tag }}"

          if [ -n "$PREV_TAG" ]; then
            CHANGELOG_LINK="**Full Changelog:** https://github.com/${{ github.repository }}/compare/$PREV_TAG...$VERSION"
            BODY="$BODY"$'\n\n'"$CHANGELOG_LINK"
          fi

          BODY="$BODY"$'\n\n'"Published by ${{ github.actor }}"

          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "body=$BODY" >> $GITHUB_OUTPUT

      - name: "Create GitHub Release"
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: ${{ steps.set_release_info.outputs.title }}
          body: ${{ steps.set_release_info.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
