name: "Debug PR Categorization"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  debug-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Get current version from package.json
        id: get_version
        run: |
          VERSION="v$(node -p 'require("./package.json").version')"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get previous Git tag
        id: get_previous_tag
        run: |
          PREV_TAG=$(git tag --sort=-creatordate | grep '^v' | grep -v "${{ steps.get_version.outputs.version }}" | head -n 1)
          echo "previous_tag=$PREV_TAG" >> $GITHUB_OUTPUT

      - name: Fetch and categorize merged PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e

          PREVIOUS_TAG=${{ steps.get_previous_tag.outputs.previous_tag }}
          if [ -z "$PREVIOUS_TAG" ]; then
            echo "⚠️ No previous tag found. Exiting."
            exit 0
          fi

          PREVIOUS_SHA=$(git rev-list -n 1 $PREVIOUS_TAG)
          PREVIOUS_DATE=$(git show -s --format=%cI $PREVIOUS_SHA)
          CURRENT_DATE=$(git show -s --format=%cI HEAD)

          echo ""
          echo "🔍 Fetching PRs merged between:"
          echo "   PREVIOUS_DATE: $PREVIOUS_DATE"
          echo "   CURRENT_DATE:  $CURRENT_DATE"

          PRS=$(gh pr list --state merged --search "merged:${PREVIOUS_DATE}..${CURRENT_DATE}" \
            --json number,title,url \
            --jq '.[] | "- [#\(.number)](\(.url)) \(.title)"')

          echo ""
          echo "🔎 All Fetched PRs:"
          echo "$PRS"

          ADDED=""
          FIXED=""

          while IFS= read -r pr; do
            if echo "$pr" | grep -Eqi '\)\s+fix:'; then
              FIXED+="$pr  # fix"$'\n'
            elif echo "$pr" | grep -Eqi '\)\s+feat:'; then
              ADDED+="$pr  # feat"$'\n'
            fi
          done <<< "$PRS"

          echo ""
          echo "✅ Categorized PRs:"
          echo "----------------------------"
          if [ -n "$ADDED" ]; then
            echo "$ADDED"
          fi
          if [ -n "$FIXED" ]; then
            echo "$FIXED"
          fi
          if [ -z "$ADDED" ] && [ -z "$FIXED" ]; then
            echo "No PRs matched 'feat:' or 'fix:'."
          fi
